# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-26 19:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=12)),
                ('background', models.TextField(verbose_name=b'Please let us know a little about your education and occupation.')),
                ('relevant_experience', models.TextField(verbose_name=b'Please let us know about any relevant experience.')),
                ('interest_reason', models.TextField(verbose_name=b'Why are you interested in becoming a Heritage Monitoring Scout?')),
                ('site_interest_type', models.CharField(choices=[(b'Prehistoric', b'Prehistoric'), (b'Historic', b'Historic'), (b'Cemeteries', b'Cemeteries'), (b'Underwater', b'Underwater'), (b'Other', b'Other')], max_length=30, verbose_name=b'What type of sites are you interested in?')),
                ('region_choices', models.CharField(choices=[(b'NW', b'Northwest'), (b'NC', b'North Central'), (b'NE', b'Northeast'), (b'CR', b'Central'), (b'WC', b'West Central'), (b'SW', b'Southwest'), (b'SE', b'Southeast')], max_length=2, verbose_name=b'Which region(s) are you interested in monitoring sites in?')),
                ('ethics_agreement', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
