# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-30 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='state',
            field=models.CharField(default=b'Florida', max_length=30),
        ),
    ]
