# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpan', '0004_auto_20171127_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedarea',
            name='category',
            field=models.CharField(choices=[(b'State Parks', b'State Parks'), (b'State Forest', b'State Forest'), (b'Fish and Wildlife Conservation Commission', b'Fish and Wildlife Conservation Commission'), (b'Aquatic Preserve', b'Aquatic Preserve')], max_length=254),
        ),
    ]
