# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpan', '0007_managedarea_sp_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedarea',
            name='category',
            field=models.CharField(choices=[(b'State Park', b'State Park'), (b'State Forest', b'State Forest'), (b'Fish and Wildlife Conservation Commission', b'Fish and Wildlife Conservation Commission'), (b'Aquatic Preserve', b'Aquatic Preserve')], max_length=254),
        ),
    ]
