# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 18:47
from __future__ import unicode_literals

from django.db import migrations
from django.core import management
from fpan.models import ManagedArea
from fpan.utils.fpan_account_utils import add_fwcc_nicknames


def load_managedareas(apps, schema_editor):

    management.call_command("loaddata", "managedareas1.json")
    management.call_command("loaddata", "managedareas2.json")
    management.call_command("loaddata", "managedareas3.json")
    management.call_command("loaddata", "managedareas4.json")
    management.call_command("loaddata", "managedareas5.json")
    management.call_command("loaddata", "managedareas6.json")

    ## these operations add some extra info to some of the managed areas
    ## that is not included in the fixture files.
    add_fwcc_nicknames()
    management.call_command('add_districts_to_state_parks')


def remove_managedareas(apps, schema_editor):

    ManagedArea.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('fpan', '0008_alter_state_park_category_value'),
    ]

    operations = [
        migrations.RunPython(load_managedareas, remove_managedareas)
    ]
