# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 18:47
from __future__ import unicode_literals

from django.db import migrations
from django.core import management

from fpan.decorators import deprecated_migration_operation

@deprecated_migration_operation
def load_managedareas(apps, schema_editor):

    management.call_command("loaddata", "managedareas1.json")
    management.call_command("loaddata", "managedareas2.json")
    management.call_command("loaddata", "managedareas3.json")
    management.call_command("loaddata", "managedareas4.json")
    management.call_command("loaddata", "managedareas5.json")
    management.call_command("loaddata", "managedareas6.json")

    ## these operations add some extra info to some of the managed areas
    ## that is not included in the fixture files.
    from fpan.utils.legacy_utils import add_fwcc_nicknames
    add_fwcc_nicknames()

@deprecated_migration_operation
def remove_managedareas(apps, schema_editor):

    from fpan.models import ManagedArea
    ManagedArea.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('fpan', '0009_alter_ma_for_wmd'),
    ]

    operations = [
        migrations.RunPython(load_managedareas, remove_managedareas)
    ]
