# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 18:47
from __future__ import unicode_literals

from django.db import migrations
from django.core import management
from fpan.models import Region


def load_regions(apps, schema_editor):

    management.call_command("loaddata", "regions.json")


def remove_regions(apps, schema_editor):

    Region.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('fpan', '0009_load_managedarea_fixtures'),
    ]

    operations = [
        migrations.RunPython(load_regions, remove_regions)
    ]
