# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-20 18:47
from __future__ import unicode_literals

from django.db import migrations
from django.core import management

from fpan.decorators import deprecated_migration_operation

@deprecated_migration_operation
def load_regions(apps, schema_editor):

    management.call_command("loaddata", "regions.json")

@deprecated_migration_operation
def remove_regions(apps, schema_editor):

    from fpan.models import Region
    Region.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('fpan', '0010_load_managedarea_fixtures'),
    ]

    operations = [
        migrations.RunPython(load_regions, remove_regions)
    ]
