# Generated by Django 2.2.9 on 2021-01-07 10:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '5605_searchexporthistory_downloadfile'),
        ('fpan', '0015_load_slr_layers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='ManagementArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('managing_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fpan.Agency')),
            ],
            options={
                'verbose_name': 'Management Area',
                'verbose_name_plural': 'Management Areas',
            },
        ),
        migrations.CreateModel(
            name='ManagementAreaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=255)),
                ('areas', models.ManyToManyField(to='fpan.ManagementArea')),
            ],
            options={
                'verbose_name': 'Management Area Group',
                'verbose_name_plural': 'Management Area Groups',
            },
        ),
        migrations.CreateModel(
            name='ManagementAreaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Management Area Type',
                'verbose_name_plural': 'Management Area Types',
            },
        ),
        migrations.AlterField(
            model_name='managedarea',
            name='agency',
            field=models.CharField(choices=[('FL Dept. of Environmental Protection, Div. of Recreation and Parks', 'FL Dept. of Environmental Protection, Div. of Recreation and Parks'), ('FL Dept. of Agriculture and Consumer Services, Florida Forest Service', 'FL Dept. of Agriculture and Consumer Services, Florida Forest Service'), ('FL Fish and Wildlife Conservation Commission', 'FL Fish and Wildlife Conservation Commission'), ('FL Dept. of Environmental Protection, Florida Coastal Office', 'FL Dept. of Environmental Protection, Florida Coastal Office'), ('FL Dept. of Environmental Protection, Office of Water Policy', 'FL Dept. of Environmental Protection, Office of Water Policy')], max_length=254),
        ),
        migrations.AlterField(
            model_name='managedarea',
            name='category',
            field=models.CharField(choices=[('State Park', 'State Park'), ('State Forest', 'State Forest'), ('Fish and Wildlife Conservation Commission', 'Fish and Wildlife Conservation Commission'), ('Aquatic Preserve', 'Aquatic Preserve'), ('Water Management District', 'Water Management District')], max_length=254),
        ),
        migrations.AlterField(
            model_name='managedarea',
            name='wmd_district',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('North Central', 'North Central'), ('West', 'West'), ('South', 'South'), ('Southwest', 'Southwest'), ('South Central', 'South Central')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.UserProfile')),
                ('area_groups', models.ManyToManyField(to='fpan.ManagementAreaGroup')),
                ('areas', models.ManyToManyField(to='fpan.ManagementArea')),
            ],
            options={
                'verbose_name': 'Manager Profile',
                'verbose_name_plural': 'Manager Profiles',
            },
            bases=('models.userprofile',),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fpan.ManagementAreaType'),
        ),
    ]
