# Generated by Django 2.2.13 on 2021-08-17 21:05

from django.db import migrations
from arches.app.models.tile import Tile

def fix_tiles(apps, schema_editor):

    tiles = Tile.objects.filter(nodegroup_id="03643bd0-d550-11e7-9629-94659cf754d0")
    site_culture_node = "036462e3-d550-11e7-932a-94659cf754d0"
    site_type_node = "036462e2-d550-11e7-a492-94659cf754d0"
    ct = 0
    for n, t in enumerate(tiles):
        updated = False
        for nid in [site_culture_node, site_type_node]:
            if t.data[nid] and not isinstance(t.data[nid], list):
                print(f"fixing: {t.resourceinstance_id} - {nid}")
                t.data[nid] = [t.data[nid]]
                updated = True
        if updated is True:
            t.save()
            Resource.objects.get(pk=t.resourceinstance_id).index()
            ct +=1

    print(f"{ct} resources fixed")

class Migration(migrations.Migration):

    dependencies = [
        ('fpan', '0016_register_site_filter'),
    ]

    operations = [
        migrations.RunPython(fix_tiles)
    ]
