# Generated by Django 3.2.14 on 2023-04-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0017_auto_20230403_1610'),
        ('fpan', '0017_fix_sitetype_siteculture_tiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagedArea',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
