# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-31 14:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fpan', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ScoutProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(default='Florida', max_length=30)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=12)),
                ('background', models.TextField(verbose_name='Please let us know a little about your education and occupation.')),
                ('relevant_experience', models.TextField(verbose_name='Please let us know about any relevant experience.')),
                ('interest_reason', models.TextField(verbose_name='Why are you interested in becoming a Heritage Monitoring Scout?')),
                ('site_interest_type', models.CharField(choices=[('Prehistoric', 'Prehistoric'), ('Historic', 'Historic'), ('Cemeteries', 'Cemeteries'), ('Underwater', 'Underwater'), ('Other', 'Other')], max_length=30, verbose_name='What type of sites are you interested in?')),
                ('ethics_agreement', models.BooleanField(default=False)),
                ('region_choices', models.ManyToManyField(to='fpan.Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms.Scout')),
            ],
        ),
    ]
