# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='middle_initial',
            field=models.CharField(default='U', max_length=1),
            preserve_default=False,
        ),
    ]
