# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-12-01 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scout',
            options={'verbose_name': 'Scout', 'verbose_name_plural': 'Scouts'},
        ),
    ]
