# Generated by Django 2.2.13 on 2021-01-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_add_landmanagement_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmanagerprofile',
            options={'verbose_name': 'Land Manager Profile', 'verbose_name_plural': 'Land Manager Profiles'},
        ),
        migrations.AddField(
            model_name='landmanagerprofile',
            name='management_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hms.ManagementAgency'),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='load_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='landmanagerprofile',
            name='grouped_areas',
            field=models.ManyToManyField(blank=True, to='hms.ManagementAreaGroup'),
        ),
        migrations.AlterField(
            model_name='landmanagerprofile',
            name='individual_areas',
            field=models.ManyToManyField(blank=True, to='hms.ManagementArea'),
        ),
        migrations.AlterField(
            model_name='landmanagerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hms.LandManager'),
        ),
    ]
