# Generated by Django 2.2.13 on 2021-08-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0008_load_extra_management_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmanager',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True, editable=False),
        ),
    ]
