# Generated by Django 2.2.13 on 2021-08-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0011_auto_20210823_1602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserXResourceInstanceAccess',
        ),
    ]
