# Generated by Django 3.2.14 on 2023-01-31 13:42

from django.db import migrations, models

from fpan.decorators import deprecated_migration_operation
from hms.models import ScoutProfile, ManagementArea

@deprecated_migration_operation
def migrate_region_choices(apps, schema_editor):
    """ Populate the new fpan_regions field with ManagementArea
    instances based on the existing region_choices field which uses
    the deprecated Region model"""
    region_lookup = {
        "Central": "FPAN Central Region",
        "East Central": "FPAN East Central Region",
        "North Central": "FPAN North Central Region",
        "Northeast": "FPAN Northeast Region",
        "Northwest": "FPAN Northwest Region",
        "Southeast": "FPAN Southeast Region",
        "Southwest": "FPAN Southwest Region",
        "West Central": "FPAN West Central Region", 
    }

    for s in ScoutProfile.objects.all():
        for r in s.region_choices.all():
            try:
                ma = ManagementArea.objects.get(name=region_lookup[r.name])
                s.fpan_regions.add(ma)
            except ManagementArea.DoesNotExist:
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0014_auto_20230131_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoutprofile',
            name='fpan_regions',
            field=models.ManyToManyField(to='hms.ManagementArea'),
        ),
        migrations.RunPython(migrate_region_choices)
    ]
