# Generated by Django 3.2.14 on 2023-02-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0014_load_nr_historic_districts'),
        ('hms', '0015_auto_20230131_1342'),
    ]

    operations = [
    ]
