# Generated by Django 3.2.14 on 2023-10-22 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '8579_alter_resourceinstance_descriptors'),
        ('hms', '0017_auto_20230403_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementagency',
            name='concept',
            field=models.ForeignKey(blank=True, limit_choices_to={'nodetype_id': 'Concept'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.concept'),
        ),
        migrations.AddField(
            model_name='managementarea',
            name='concept',
            field=models.ForeignKey(blank=True, limit_choices_to={'nodetype_id': 'Concept'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.concept'),
        ),
    ]
