# Generated by Django 3.2.14 on 2026-04-01 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hms", "0019_auto_20260401_1033"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scoutprofile",
            name="fpan_regions",
        ),
    ]
