# Generated by Django 3.2.14 on 2026-04-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0020_remove_scoutprofile_fpan_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementareagroup',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
