# Generated by Django 4.2.30 on 2026-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hms", "0021_alter_managementareagroup_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="managementarea",
            name="management_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Federal", "Federal"),
                    ("State", "State"),
                    ("County", "County"),
                    ("City", "City"),
                    ("Private", "Private"),
                ],
                help_text="Used for internal management. Not linked to permissions rules.",
                max_length=25,
                null=True,
            ),
        ),
    ]
